---
- name: playbook to provision most of the MoodleBox
  hosts: all
  vars:
    ansible_user: 'root'
  become: 'true'

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: include customised variables
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

  roles:
    - rpi-settings
    - apt
    - { role: firmware, when: moodlebox_update_firmware }
    - { role: hostname, when: moodlebox_set_hostname }
    - useraccount
    - { role: timezone, when: moodlebox_set_timezone }
    - { role: locales, when: moodlebox_set_locale }
    - wifi
    - database
    - packages
    - special-packages
    - install
    - network
    - moodle
    - branding
    - cleanup
