---
- name: playbook to provision most of the MoodleBox
  hosts: all
  vars:
    ansible_user: 'root'
  become: 'true'

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: include customised variables
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

  roles:
    - { role: firmware, when: moodlebox_update_firmware }
    - bootstrap
    - install
    - network
    - moodle
    - cleanup
