---
- name: restart cron
  service:
    name: 'cron'
    state: 'restarted'

- name: restart rsyslog
  service:
    name: 'rsyslog'
    state: 'restarted'

- name: restart incron
  service:
    name: 'incron'
    state: 'restarted'

- name: restart web services
  systemd:
    name: '{{ item }}'
    state: 'restarted'
    daemon_reload: 'yes'
  with_items:
    - 'nginx'
    - 'php7.3-fpm'
