---
- name: configure nginx
  template:
    src: 'etc/nginx/sites-available/default.j2'
    dest: '/etc/nginx/sites-available/default'
  notify: restart web services

- name: install SSL certificates
  import_tasks: certs.yml
  notify: restart web services

- name: reboot machine
  shell: 'sleep 2 && shutdown -r now'
  async: 1
  poll: 0
  ignore_errors: true
  when: network_configured is successful

- name: wait for machine to come back
  wait_for:
    host: '{{ ansible_host | default(inventory_hostname) }}'
    port: 22
    state: 'started'
    delay: 10
    timeout: 60
  delegate_to: localhost
  become: false

- name: configure IP forwarding
  import_tasks: iproute.yml
  notify: restart networking

- meta: flush_handlers
