---

- name: configure dhcpcd with static IP address {{ moodlebox_ip_address | ipaddr('host') }}
  blockinfile:
    path: '/etc/dhcpcd.conf'
    block: |
      interface wlan0
      static ip_address={{ moodlebox_ip_address | ipaddr('host') }}
  notify: restart networking

- name: update access point configuration file
  template:
    src: 'etc/hostapd/hostapd.conf.j2'
    dest: '/etc/hostapd/hostapd.conf'
  notify: restart networking

- name: update access point settings
  lineinfile:
    path: '/etc/default/hostapd'
    regexp: '^#?DAEMON_CONF'
    line: 'DAEMON_CONF="/etc/hostapd/hostapd.conf"'
  notify: restart networking

- name: unmask, enable and start hostapd
  systemd:
    name: 'hostapd'
    state: 'started'
    enabled: 'yes'
    masked: 'no'

- name: update dnsmasq configuration
  template:
    src: 'etc/dnsmasq.conf.j2'
    dest: '/etc/dnsmasq.conf'
  notify: restart networking

- name: update dnsmasq service file
  blockinfile:
    path: '/lib/systemd/system/dnsmasq.service'
    insertbefore: '^\[Install\]\s*$'
    block: |
      RestartSec=5
      Restart=on-failure
  notify: restart networking

- name: configure zeroconf service
  template:
    src: 'etc/avahi/services/moodlebox.service.j2'
    dest: '/etc/avahi/services/{{ moodlebox_hostname }}.service'
  notify: restart networking
  register: network_configured

- name: configure nginx
  template:
    src: 'etc/nginx/sites-available/default.j2'
    dest: '/etc/nginx/sites-available/default'
  notify: restart web services

- name: reboot machine
  shell: 'sleep 2 && shutdown -r now'
  async: 1
  poll: 0
  ignore_errors: true
  when: network_configured is successful

- name: wait for machine to come back
  wait_for:
    host: '{{ ansible_host | default(inventory_hostname) }}'
    port: 22
    state: 'started'
    delay: 10
    timeout: 60
  delegate_to: localhost
  become: false

- name: configure IP forwarding
  import_tasks: iproute.yml
  notify: restart networking
