---
- name: clean previous installation
  import_tasks: clean.yml

- name: create database
  import_tasks: db.yml

- name: configure Moodle site summary
  import_tasks: summary.yml

- name: get Moodle and install it
  import_tasks: coreinstall.yml

- name: get MoodleBox plugin and install it
  import_tasks: moodleboxplugin.yml

- name: install MathJax library
  import_tasks: mathjax.yml

- name: compile themes scss
  import_tasks: themes.yml

- name: install adminer latest release
  get_url:
    url: 'https://www.adminer.org/latest.php'
    dest: '{{ moodlebox_moodle_source_dir }}/adminer.php'
    owner: 'www-data'
    group: '{{ moodlebox_username }}'
    mode: '0664'

- name: copy root CA certificate
  copy:
    src: 'home/files/moodleboxCA.crt'
    dest: '/home/{{ moodlebox_username }}/files/moodleboxCA.crt'
    owner: '{{ moodlebox_username }}'
    group: 'www-data'

- name: configure crons
  import_tasks: cron.yml

- meta: flush_handlers
