---
- name: configure zeroconf service
  template:
    src: 'etc/avahi/services/moodlebox.service.j2'
    dest: '/etc/avahi/services/{{ moodlebox_hostname }}.service'
  register: network_configured
  notify: restart networking
