---

- name: write version file
  template:
    src: 'etc/moodlebox-info.j2'
    dest: '/etc/moodlebox-info'

- name: update motd
  template:
    src: 'etc/motd.j2'
    dest: '/etc/motd'

- name: copy ascii logo file
  copy:
    src: 'etc/moodlebox-logo.txt'
    dest: '/etc/moodlebox-logo.txt'
    mode: 0644

- name: copy script to display ascii logo
  copy:
    src: 'etc/update-motd.d/20-logo'
    dest: '/etc/update-motd.d/20-logo'
    mode: 0755
