---

- name: copy usbmount deb package file
  copy:
    src: 'usbmount_0.0.24_all.deb'
    dest: '/tmp/usbmount.deb'

- name: install usbmount package
  apt:
    deb: '/tmp/usbmount.deb'

- name: delete usbmount deb package file
  file:
    path: '/tmp/usbmount.deb'
    state: 'absent'

- name: copy nodogsplash deb package file
  copy:
    src: 'nodogsplash_3.3.2-1_armhf.deb'
    dest: '/tmp/nodogsplash.deb'

- name: install nodogsplash package
  apt:
    deb: '/tmp/nodogsplash.deb'

- name: delete nodogsplash deb package file
  file:
    path: '/tmp/nodogsplash.deb'
    state: 'absent'

- name: configure nodogsplash captive portal
  template:
    src: 'etc/nodogsplash/nodogsplash.conf.j2'
    dest: '/etc/nodogsplash/nodogsplash.conf'

- name: disable nodogsplash service at startup
  systemd:
    name: 'nodogsplash'
    state: stopped
    enabled: no
    masked: no

