---

- name: install phpMyAdmin package
  apt:
    pkg: 'phpmyadmin'
    state: 'present'
    install_recommends: 'false'
  register: phpmyadmin_installed
  until: phpmyadmin_installed is succeeded

- name: install custom phpMyAdmin configuration file
  copy:
    src: 'etc/phpmyadmin/conf.d/moodlebox.inc.php'
    dest: '/etc/phpmyadmin/conf.d/moodlebox.inc.php'
    mode: 0644

- name: copy usbmount deb package file
  copy:
    src: 'usbmount_0.0.24_all.deb'
    dest: '/tmp/usbmount_0.0.24_all.deb'

- name: install usbmount package
  apt:
    deb: '/tmp/usbmount_0.0.24_all.deb'

- name: delete usbmount deb package file
  file:
    path: '/tmp/usbmount_0.0.24_all.deb'
    state: 'absent'

- name: copy nodogsplash deb package file
  copy:
    src: 'nodogsplash_3.3.1-1_armhf.deb'
    dest: '/tmp/nodogsplash_3.3.1-1_armhf.deb'

- name: install nodogsplash package
  apt:
    deb: '/tmp/nodogsplash_3.3.1-1_armhf.deb'

- name: delete nodogsplash deb package file
  file:
    path: '/tmp/nodogsplash_3.3.1-1_armhf.deb'
    state: 'absent'

- name: configure nodogsplash captive portal
  template:
    src: 'etc/nodogsplash/nodogsplash.conf.j2'
    dest: '/etc/nodogsplash/nodogsplash.conf'

- name: disable nodogsplash service at startup
  systemd:
    name: 'nodogsplash'
    state: stopped
    enabled: no
    masked: no

