---

- name: add script to resize partition on first boot
  copy:
    src: 'etc/init.d/resize2fs_once'
    dest: '/etc/init.d/resize2fs_once'
    mode: 0755

- name: enable ntfs and exfat formats mounting by usbmount
  replace:
    path: '/etc/usbmount/usbmount.conf'
    regexp: '^FILESYSTEMS=.*$'
    replace: 'FILESYSTEMS="vfat exfat ntfs fuseblk ext2 ext3 ext4 hfsplus"'

- name: add root to allowed incron users
  lineinfile:
    path: '/etc/incron.allow'
    line: 'root'
  notify: restart incron

- name: remove default nodogsplash files
  file:
    path: '/etc/nodogsplash/htdocs'
    state: 'absent'

- name: update nodogsplash files
  copy:
    src: 'etc/nodogsplash/htdocs'
    dest: '/etc/nodogsplash'
    mode: 0644
