---

- name: add script to resize partition on first boot
  copy:
    src: 'etc/init.d/resize2fs_once'
    dest: '/etc/init.d/resize2fs_once'
    mode: 0755

- name: enable ntfs and exfat formats mounting by usbmount
  replace:
    path: '/etc/usbmount/usbmount.conf'
    regexp: '^FILESYSTEMS=.*$'
    replace: 'FILESYSTEMS="vfat exfat ntfs fuseblk ext2 ext3 ext4 hfsplus"'

- name: add root to allowed incron users
  lineinfile:
    path: '/etc/incron.allow'
    line: 'root'
  notify: restart incron

- name: remove default nodogsplash files
  file:
    path: '/etc/nodogsplash/htdocs'
    state: 'absent'

- name: update nodogsplash files
  copy:
    src: 'etc/nodogsplash/htdocs'
    dest: '/etc/nodogsplash'
    mode: 0644

- name: set umask for nginx and php-fpm services
  lineinfile:
    path: '{{ item }}'
    line: 'UMask=0002'
    insertafter: '^\[Service\].*'
  with_items:
    - '/lib/systemd/system/nginx.service'
    - '/lib/systemd/system/php7.3-fpm.service'
  notify: restart web services

- name: set group for php-fpm process
  lineinfile:
    path: '/etc/php/7.3/fpm/pool.d/www.conf'
    regexp: '^group\s*=\s*www-data.*'
    line: 'group = {{ moodlebox_username }}'
  notify: restart web services
